# Generated by Django 5.0.4 on 2024-07-06 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0004_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='images/')),
                ('price', models.FloatField()),
                ('old_price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
