# Generated by Django 5.0.3 on 2024-04-05 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0003_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCheck',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
