# Generated by Django 5.0.3 on 2024-04-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0004_fieldcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcheck',
            name='_db_col',
            field=models.BigIntegerField(db_column='auto_db_col', default=7),
            preserve_default=False,
        ),
    ]
