# Generated by Django 5.0.4 on 2024-04-05 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0006_alter_fieldcheck__db_col'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FieldCheck',
        ),
    ]
