# Generated by Django 5.0.4 on 2024-04-09 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0007_delete_fieldcheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='month',
            field=models.CharField(choices=[('JANUARY', 'January'), ('FEBRUARY', 'February'), ('MARCH', 'March'), ('DECEMBER', 'December')], default='JANUARY', max_length=9),
        ),
    ]
