# Generated by Django 5.0.4 on 2024-04-09 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0010_tag_profile_article2'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
