# Generated by Django 4.2.5 on 2024-04-10 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0011_book_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posting_date', models.DateTimeField(auto_now_add=True)),
                ('warehosue', models.CharField(max_length=50)),
                ('stock_type', models.CharField(choices=[('Material Receipt', 'Material Receipt')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StockEntryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_qty', models.FloatField()),
                ('price', models.DecimalField(decimal_places=3, max_digits=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product_management.stockentry')),
            ],
        ),
    ]
