# Generated by Django 4.2.5 on 2024-04-10 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0012_stockentry_stockentryitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentryitems',
            name='price',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
