# Generated by Django 4.2.5 on 2024-04-10 03:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0013_alter_stockentryitems_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentryitems',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product_management.stockentry'),
        ),
    ]
