# Generated by Django 4.2.5 on 2024-04-11 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0014_alter_stockentryitems_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_percentage', models.DecimalField(decimal_places=2, default=50.0, max_digits=3)),
            ],
            options={
                'db_table': 'product_discount',
            },
        ),
        migrations.CreateModel(
            name='DiscountInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_percentage', models.DecimalField(db_column='product_d_percentage', decimal_places=2, default=50.0, max_digits=3)),
            ],
            options={
                'db_table': 'product_discounts',
                'db_table_comment': 'it is used to specify product discounts.',
            },
        ),
    ]
