# Generated by Django 4.2.5 on 2024-04-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0015_discount_discountinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTypesCheckL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bike_name', models.CharField(max_length=100)),
            ],
        ),
    ]
