# Generated by Django 4.2.5 on 2024-04-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0016_fieldtypescheckl'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl',
            name='title',
            field=models.CharField(default='null', max_length=100),
            preserve_default=False,
        ),
    ]
