# Generated by Django 4.2.5 on 2024-04-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0017_fieldtypescheckl_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtypescheckl',
            name='bike_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
