# Generated by Django 4.2.5 on 2024-04-12 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0023_alter_fieldtypescheckl_bike_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl',
            name='dynamic_choices',
            field=models.CharField(choices=[('db', 'label'), (None, 'Select Choice')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldtypescheckl',
            name='model',
            field=models.CharField(choices=[('FZS', 'fzs'), ('FZX', 'fzx')], default='FZS', max_length=100),
        ),
        migrations.AddField(
            model_name='fieldtypescheckl',
            name='year',
            field=models.CharField(choices=[('2012', '2k12'), ('2k13', '2k13')], default='FZS', max_length=100, null=True),
        ),
    ]
