# Generated by Django 4.2.5 on 2024-04-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0024_fieldtypescheckl_dynamic_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl',
            name='choices',
            field=models.CharField(choices=[('Audio', (('vinyl', 'Vinyl'), ('cd', 'CD'))), ('Video', (('vhs', 'VHS Tape'), ('dvd', 'DVD'))), ('unknown', 'Unknown')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fieldtypescheckl',
            name='dynamic_choices',
            field=models.CharField(choices=[('db', 'label'), (None, 'Select Choice'), ('db', 'hey db')], max_length=100),
        ),
    ]
