# Generated by Django 5.0.4 on 2024-04-12 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0025_fieldtypescheckl_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl',
            name='cls_choices',
            field=models.CharField(choices=[('iphone', 'Iphone')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldtypescheckl',
            name='enum_choices',
            field=models.CharField(choices=[('bj', 'Bajaj'), ('hd', 'Honda')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
