# Generated by Django 5.0.4 on 2024-04-12 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0026_fieldtypescheckl_cls_choices_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl',
            name='suit',
            field=models.IntegerField(choices=[(1, 'Diamond'), (2, 'Spade'), (3, 'Heart'), (4, 'Club')], default=1),
            preserve_default=False,
        ),
    ]
