# Generated by Django 5.0.4 on 2024-04-12 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0028_fieldtypescheckl_moon_landing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtypescheckl',
            name='moon_landing',
        ),
    ]
