# Generated by Django 5.0.4 on 2024-04-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0031_fieldtypescheckl_dd_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtypescheckl',
            name='year',
            field=models.CharField(choices=[(None, 'Please Select Choice..'), ('2012', '2k12'), ('2k13', '2k13')], default='FZS', max_length=100, null=True),
        ),
    ]
