# Generated by Django 5.0.4 on 2024-04-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0034_fieldtypescheckl_dd_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl',
            name='json_ob',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
