# Generated by Django 5.0.4 on 2024-04-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0035_fieldtypescheckl_json_ob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtypescheckl',
            name='json_ob',
            field=models.JSONField(editable=False),
        ),
    ]
