# Generated by Django 5.0.4 on 2024-04-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0036_alter_fieldtypescheckl_json_ob'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl',
            name='checking',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
