# Generated by Django 5.0.4 on 2024-04-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0037_fieldtypescheckl_checking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtypescheckl',
            name='checking',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
