# Generated by Django 5.0.4 on 2024-04-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0041_alter_fieldtypescheckl_checking'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl',
            name='checking_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
