# Generated by Django 5.0.4 on 2024-04-12 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0045_alter_fieldtypescheckl_suit'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTypesCheckL2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product_management.fieldtypescheckl', verbose_name='One Army')),
            ],
        ),
    ]
