# Generated by Django 5.0.4 on 2024-04-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0049_alter_fieldtypescheckl2_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtypescheckl2',
            name='pub_date',
            field=models.DateField(unique=True),
        ),
    ]
