# Generated by Django 5.0.4 on 2024-04-12 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0051_alter_fieldtypescheckl2_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtypescheckl2',
            name='many',
            field=models.ManyToManyField(to='product_management.fieldtypescheckl'),
        ),
        migrations.AlterField(
            model_name='fieldtypescheckl2',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='one_to_one', to='product_management.fieldtypescheckl', unique_for_date='pub_date', verbose_name='One Army'),
        ),
    ]
