# Generated by Django 5.0.4 on 2024-04-12 03:48

import django.db.models.deletion
import product_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0052_alter_fieldtypescheckl2_many_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='valida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validate_field', to='product_management.fieldtypescheckl', validators=[product_management.models.validate_1, product_management.models.validate_2]),
        ),
    ]
