# Generated by Django 5.0.4 on 2024-04-12 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0053_fieldtypescheckl2_valida'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='date_now',
            field=models.DateField(auto_now=True),
        ),
    ]
