# Generated by Django 5.0.4 on 2024-04-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0054_fieldtypescheckl2_date_now'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='datetime_now',
            field=models.DateField(auto_now=True),
        ),
    ]
