# Generated by Django 5.0.4 on 2024-04-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0055_fieldtypescheckl2_datetime_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtypescheckl2',
            name='datetime_now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
