# Generated by Django 5.0.4 on 2024-04-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0059_fieldtypescheckl2_email_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='file_f',
            field=models.FileField(default='', upload_to='\x0ciles'),
            preserve_default=False,
        ),
    ]
