# Generated by Django 5.0.4 on 2024-04-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0061_alter_fieldtypescheckl2_file_f'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='file_d',
            field=models.FileField(default='', upload_to='files/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
