# Generated by Django 5.0.4 on 2024-04-13 02:09

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0063_fieldtypescheckl2_file_fun'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='file_stor',
            field=models.FileField(default='', upload_to=django.core.files.storage.FileSystemStorage(location='/system_storage')),
            preserve_default=False,
        ),
    ]
