# Generated by Django 5.0.4 on 2024-04-13 03:26

import product_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0064_fieldtypescheckl2_file_stor'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='file_path',
            field=models.FilePathField(default='', path=product_management.models.get_file_path),
            preserve_default=False,
        ),
    ]
