# Generated by Django 5.0.4 on 2024-04-14 02:36

import product_management.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0065_fieldtypescheckl2_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='gen_field',
            field=models.GeneratedField(db_persist=True, expression=models.F('file_path'), output_field=models.FilePathField()),
        ),
        migrations.AlterField(
            model_name='fieldtypescheckl2',
            name='file_path',
            field=models.FilePathField(allow_folders=True, path=product_management.models.get_file_path, recursive=True),
        ),
    ]
