# Generated by Django 5.0.4 on 2024-04-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0066_fieldtypescheckl2_gen_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='fip_ad',
            field=models.GenericIPAddressField(null=True, verbose_name='FIP Address'),
        ),
    ]
