# Generated by Django 5.0.4 on 2024-04-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0067_fieldtypescheckl2_fip_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='img_f',
            field=models.ImageField(default=1, height_field='img_h', upload_to='images/', width_field='img_w'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='img_h',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='img_w',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
