# Generated by Django 5.0.4 on 2024-04-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0069_fieldtypescheckl2_json_ob'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='chr',
            field=models.CharField(default='india', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fieldtypescheckl2',
            name='slug_f',
            field=models.SlugField(default='www.cc.com', max_length=100),
            preserve_default=False,
        ),
    ]
