# Generated by Django 5.0.4 on 2024-04-14 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0070_fieldtypescheckl2_chr_fieldtypescheckl2_slug_f'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCheck3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('URL', models.SlugField(max_length=100)),
            ],
        ),
    ]
