# Generated by Django 5.0.4 on 2024-04-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0071_fieldcheck3'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcheck3',
            name='url_fiel',
            field=models.URLField(default='https://www.ac.com', max_length=100),
            preserve_default=False,
        ),
    ]
