# Generated by Django 5.0.4 on 2024-04-14 08:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0072_fieldcheck3_url_fiel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckUUID',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
