# Generated by Django 5.0.4 on 2024-04-14 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0073_checkuuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtypescheckl2',
            name='json_ob',
        ),
    ]
