# Generated by Django 5.0.4 on 2024-04-14 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0075_forignopts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forignopts',
            name='b',
            field=models.ForeignKey(limit_choices_to={'author': 1}, on_delete=django.db.models.deletion.DO_NOTHING, to='product_management.book'),
        ),
        migrations.AlterField(
            model_name='forignopts',
            name='dis',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product_management.discount'),
        ),
        migrations.AlterField(
            model_name='forignopts',
            name='filed_l',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='product_management.fieldtypescheckl'),
        ),
    ]
