# Generated by Django 5.0.4 on 2024-04-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0077_alter_forignopts_b'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcheck3',
            name='URL',
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
