# Generated by Django 5.0.4 on 2024-04-14 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0078_alter_fieldcheck3_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forignopts',
            name='filed_c3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='product_management.fieldcheck3', to_field='URL'),
        ),
    ]
