# Generated by Django 5.0.4 on 2024-04-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0079_alter_forignopts_filed_c3'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', models.ManyToManyField(to='product_management.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(to='product_management.person'),
        ),
    ]
