# Generated by Django 5.0.4 on 2024-04-15 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0081_group_title_person_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(null=True, to='product_management.person'),
        ),
    ]
