# Generated by Django 5.0.4 on 2024-04-15 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0083_alter_group_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='uuids',
            field=models.ManyToManyField(blank=True, null=True, to='product_management.checkuuid'),
        ),
    ]
