# Generated by Django 5.0.4 on 2024-04-15 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0085_group_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='group_1',
            field=models.ManyToManyField(related_name='group_1', to='product_management.group'),
        ),
    ]
