# Generated by Django 5.0.4 on 2024-04-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0086_person_group_1'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('following', models.ManyToManyField(related_name='followers', to='product_management.user')),
            ],
        ),
        migrations.CreateModel(
            name='User_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('following', models.ManyToManyField(related_name='followers', to='product_management.user_1')),
            ],
        ),
    ]
