# Generated by Django 5.0.4 on 2024-04-15 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0087_user_user_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='product_management.user'),
        ),
    ]
