# Generated by Django 5.0.4 on 2024-04-15 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0088_alter_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_1',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followers', to='product_management.user_1'),
        ),
    ]
