# Generated by Django 5.0.4 on 2024-04-15 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0090_group_1_person_1_membership_1_group_1_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('child_field', models.CharField(max_length=100)),
                ('parent_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='child_1', serialize=False, to='product_management.parent')),
            ],
            bases=('product_management.parent',),
        ),
    ]
