# Generated by Django 5.0.4 on 2024-04-15 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0091_parent_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_field', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='child',
            name='parent_link',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='child_1', related_query_name='child_1_query', serialize=False, to='product_management.parent'),
        ),
        migrations.CreateModel(
            name='Child2',
            fields=[
                ('parent_2_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='product_management.parent_2')),
                ('child_fields_1', models.CharField(max_length=100)),
                ('parent_links_1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child2', related_query_name='child_2_query', to='product_management.parent')),
            ],
            bases=('product_management.parent_2',),
        ),
    ]
