# Generated by Django 5.0.4 on 2024-04-16 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0095_car_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
