# Generated by Django 5.0.4 on 2024-04-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0096_alter_car_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model_no',
            field=models.CharField(default=2, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
