# Generated by Django 5.0.4 on 2024-04-16 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0097_car_model_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='model_no',
            new_name='model_nos',
        ),
    ]
