# Generated by Django 5.0.4 on 2024-06-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0099_group_1_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtypescheckl',
            name='dd_default',
            field=models.CharField(blank=True, db_default='i am', max_length=10),
        ),
    ]
