# Generated by Django 5.0.4 on 2024-06-13 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0100_alter_fieldtypescheckl_dd_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldtypescheckl',
            name='dd_default',
            field=models.CharField(blank=True, db_default='i am', max_length=100),
        ),
        migrations.AlterField(
            model_name='fieldtypescheckl',
            name='dd_index',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
