# Generated by Django 5.0.4 on 2024-06-30 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_management', '0101_alter_fieldtypescheckl_dd_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fieldtypescheckl2',
            name='gen_field',
        ),
    ]
