# Generated by Django 5.0.4 on 2024-04-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCheck',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('_db_col', models.BigIntegerField(db_column='auto_db_col', default=8, error_messages={'unique': 'The field expected to be unique'})),
            ],
        ),
    ]
