# Generated by Django 5.0.4 on 2024-06-30 09:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('des', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldCheck',
            fields=[
                ('auto_field', models.AutoField(primary_key=True, serialize=False)),
                ('_db_col', models.BigIntegerField(db_column='auto_db_col', default=8)),
                ('_blank', models.BinaryField(blank=True)),
                ('_default', models.BooleanField(default=False)),
                ('_help_txt', models.CharField(blank=True, help_text='Help text working', max_length=10)),
                ('_editable_1', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('_date', models.DateField(default=datetime.date.today)),
                ('date_auto', models.DateField(null=True)),
                ('_err_msg', models.DateTimeField(error_messages={'null': "The fiels can't be empty."}, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FieldCheck2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(error_messages={'blank': "This field can't be blank", 'invalid': "This field can't be invalid", 'required': "Thid field can't be empty", 'unique': 'The field must be unique.'}, max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TestMigrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
