# Generated by Django 5.0.4 on 2024-06-30 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testmigrate',
            old_name='name',
            new_name='names',
        ),
    ]
