# Generated by Django 5.0.4 on 2024-04-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_fieldcheck__blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcheck',
            name='_default',
            field=models.BooleanField(default=False),
        ),
    ]
