# Generated by Django 5.0.4 on 2024-04-06 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_fieldcheck__default'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcheck',
            name='_help_txt',
            field=models.CharField(blank=True, help_text='Help text working', max_length=10),
        ),
    ]
