# Generated by Django 5.0.4 on 2024-04-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_fieldcheck__help_txt'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcheck',
            name='_editable_1',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
