# Generated by Django 5.0.4 on 2024-04-06 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_fieldcheck__editable_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcheck',
            name='_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='fieldcheck',
            name='_db_col',
            field=models.BigIntegerField(db_column='auto_db_col', default=8),
        ),
        migrations.AlterField(
            model_name='fieldcheck',
            name='_editable_1',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
