# Generated by Django 5.0.4 on 2024-04-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_fieldcheck__date_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcheck',
            name='_editable_1',
            field=models.CharField(editable=False, max_length=100, null=True),
        ),
    ]
