# Generated by Django 5.0.4 on 2024-04-06 02:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_alter_fieldcheck__editable_1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fieldcheck',
            old_name='_date_1',
            new_name='date_auto',
        ),
    ]
