# Generated by Django 5.0.4 on 2024-04-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_rename__date_1_fieldcheck_date_auto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcheck',
            name='date_auto',
            field=models.DateField(null=True),
        ),
    ]
