# Generated by Django 5.0.4 on 2024-04-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_alter_fieldcheck_date_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldcheck',
            name='_err_msg',
            field=models.DateTimeField(auto_now_add=True, error_messages={'null': "The fiels can't be empty."}, null=True),
        ),
    ]
