# Generated by Django 5.0.4 on 2024-04-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_fieldcheck__err_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcheck',
            name='_err_msg',
            field=models.DateTimeField(error_messages={'null': "The fiels can't be empty."}, null=True),
        ),
    ]
