# Generated by Django 5.0.4 on 2024-04-06 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_alter_fieldcheck__err_msg'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldCheck2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='fieldcheck',
            name='_editable_1',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
