# Generated by Django 5.0.4 on 2024-04-06 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_fieldcheck2_alter_fieldcheck__editable_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcheck2',
            name='first_name',
            field=models.CharField(error_messages={'blank': "This field can't be blank", 'null': "Thid field can't be empty"}, max_length=10),
        ),
    ]
