# Generated by Django 5.0.4 on 2024-04-06 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_fieldcheck2_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldcheck2',
            name='first_name',
            field=models.CharField(error_messages={'blank': "This field can't be blank", 'invalid': "This field can't be invalid", 'null': "Thid field can't be empty", 'unique': 'The field must be unique.'}, max_length=10, unique=True),
        ),
    ]
