# Generated by Django 5.0.4 on 2024-04-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0002_production'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='modified',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
