# Generated by Django 5.0.4 on 2024-04-30 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0003_entry_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='entry',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='Learning_ORM_queries.entry'),
            preserve_default=False,
        ),
    ]
