# Generated by Django 5.0.4 on 2024-05-08 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0010_alter_location_parent_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_model', models.CharField(max_length=100)),
                ('colour', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
