# Generated by Django 5.0.4 on 2024-05-09 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0012_product'),
        ('product_management', '0098_rename_model_no_car_model_nos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='product_management.category', verbose_name='Category Name'),
        ),
    ]
