# Generated by Django 5.0.4 on 2024-05-28 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0014_product_level'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['headline'], 'verbose_name': 'Entry Verbosue'},
        ),
    ]
