# Generated by Django 5.0.4 on 2024-05-28 01:53

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0015_alter_entry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('info', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'meta_learning',
                'base_manager_name': 'custom_manager',
            },
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
