# Generated by Django 5.0.4 on 2024-05-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0016_learnmeta'),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name='learnmeta',
            table_comment='User to learn meta in django',
        ),
    ]
