# Generated by Django 5.0.4 on 2024-05-28 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0018_alter_learnmeta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnmeta',
            options={},
        ),
    ]
