# Generated by Django 5.0.4 on 2024-05-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0022_alter_learnmeta_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnmeta',
            name='product',
            field=models.ManyToManyField(to='Learning_ORM_queries.product'),
        ),
    ]
