# Generated by Django 5.0.4 on 2024-05-28 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0024_alter_learnmeta_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnmeta',
            options={'base_manager_name': 'custom_manager', 'default_manager_name': 'custom_manager', 'default_related_name': 'get_meta', 'get_latest_by': 'age'},
        ),
    ]
