# Generated by Django 5.0.4 on 2024-05-28 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0026_alter_learnmeta_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnManaged',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Testing Managed',
                'managed': False,
            },
        ),
    ]
