# Generated by Django 5.0.4 on 2024-05-28 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0027_learnmanaged'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='learnmanaged',
            table='testing_managed',
        ),
    ]
