# Generated by Django 5.0.4 on 2024-05-30 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0028_alter_learnmanaged_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['level']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='learnmeta',
            order_with_respect_to='',
        ),
        migrations.RemoveField(
            model_name='learnmeta',
            name='product',
        ),
        migrations.AddField(
            model_name='learnmeta',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='porducts', to='Learning_ORM_queries.product'),
            preserve_default=False,
        ),
    ]
