# Generated by Django 5.0.4 on 2024-05-30 16:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0029_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnmeta',
            name='product_forign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='porducts', to='Learning_ORM_queries.product'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='learnmeta',
            name='product',
        ),
        migrations.AddField(
            model_name='learnmeta',
            name='product',
            field=models.ManyToManyField(to='Learning_ORM_queries.product'),
        ),
    ]
