# Generated by Django 5.0.4 on 2024-05-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0030_learnmeta_product_forign_remove_learnmeta_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-level']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='learnmeta',
            order_with_respect_to='product_forign',
        ),
    ]
