# Generated by Django 5.0.4 on 2024-05-30 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0031_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnmeta',
            options={'base_manager_name': 'custom_manager', 'default_manager_name': 'custom_manager', 'default_related_name': 'get_meta', 'get_latest_by': '-age', 'ordering': ['age']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='learnmeta',
            order_with_respect_to=None,
        ),
    ]
