# Generated by Django 5.0.4 on 2024-05-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0038_person_myperson'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='learnmanaged',
            options={'managed': False, 'select_on_save': True},
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name'], name='Learning_OR_first_n_1414ee_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'last_name'], name='Learning_OR_first_n_04e579_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name'], name='first_name_indexing'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['first_name', 'last_name'], name='first_name_last_name_indexing'),
        ),
    ]
