# Generated by Django 5.0.4 on 2024-05-31 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0040_remove_person_learning_or_first_n_04e579_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person Rename'},
        ),
    ]
