# Generated by Django 5.0.4 on 2024-05-31 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0041_alter_person_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Person Rename', 'verbose_name_plural': 'Persons Named'},
        ),
    ]
