# Generated by Django 5.0.4 on 2024-06-03 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0044_learnvalidate'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnvalidate',
            name='uni_field',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
