# Generated by Django 5.0.4 on 2024-06-06 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0050_bankcustomer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankcustomer',
            options={'ordering': ['customer_name']},
        ),
    ]
