# Generated by Django 5.0.4 on 2024-06-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0051_alter_bankcustomer_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankcustomer',
            options={'ordering': ['state_name'], 'verbose_name': 'Meta Working'},
        ),
        migrations.AddField(
            model_name='bankcustomer',
            name='learn_validate',
            field=models.ManyToManyField(to='Learning_ORM_queries.learnvalidate'),
        ),
    ]
