# Generated by Django 5.0.4 on 2024-06-07 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0052_alter_bankcustomer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_name', models.CharField(max_length=100)),
                ('country_name', models.CharField(max_length=100)),
                ('cust_name', models.CharField(max_length=100)),
                ('learn_validate', models.ManyToManyField(to='Learning_ORM_queries.learnvalidate')),
            ],
            options={
                'verbose_name': 'Meta Working',
                'ordering': ['state_name'],
                'abstract': False,
            },
        ),
    ]
