# Generated by Django 5.0.4 on 2024-06-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0053_shopcustomer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcustomer',
            options={},
        ),
        migrations.AlterField(
            model_name='bankcustomer',
            name='learn_validate',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='Learning_ORM_queries.learnvalidate'),
        ),
        migrations.AlterField(
            model_name='shopcustomer',
            name='learn_validate',
            field=models.ManyToManyField(related_name='%(app_label)s_%(class)s_related', related_query_name='%(app_label)s_%(class)ss', to='Learning_ORM_queries.learnvalidate'),
        ),
    ]
