# Generated by Django 5.0.4 on 2024-06-08 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0054_alter_shopcustomer_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IphoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Iphone',
            fields=[
                ('iphonemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Learning_ORM_queries.iphonemodel')),
                ('name', models.CharField(max_length=100)),
            ],
            bases=('Learning_ORM_queries.iphonemodel',),
        ),
    ]
