# Generated by Django 5.0.4 on 2024-06-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0055_iphonemodel_iphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iphonemodel',
            name='model_no',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
