# Generated by Django 5.0.4 on 2024-06-08 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0056_alter_iphonemodel_model_no'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='iphone',
            options={'ordering': []},
        ),
        migrations.AlterModelOptions(
            name='iphonemodel',
            options={'get_latest_by': 'model_no', 'ordering': ['model_no']},
        ),
        migrations.AddField(
            model_name='iphone',
            name='shopcustomer',
            field=models.ManyToManyField(to='Learning_ORM_queries.shopcustomer'),
        ),
    ]
