# Generated by Django 5.0.4 on 2024-06-08 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0058_iphone_model_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyLearn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_name', models.CharField(max_length=100)),
                ('order_no', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChildProx',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Learning_ORM_queries.proxylearn',),
        ),
    ]
