# Generated by Django 5.0.4 on 2024-06-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0060_article_book_alter_childprox_options_bookreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='proxylearn',
            name='review',
            field=models.ManyToManyField(to='Learning_ORM_queries.rating'),
        ),
    ]
