# Generated by Django 5.0.4 on 2024-06-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0061_rating_proxylearn_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_keyword', models.CharField(max_length=100)),
            ],
        ),
    ]
