# Generated by Django 5.0.4 on 2024-06-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0062_searchkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkey',
            name='full_description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
