# Generated by Django 5.0.4 on 2024-06-14 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0063_searchkey_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkey',
            name='proxy_learn',
            field=models.ManyToManyField(blank=True, to='Learning_ORM_queries.proxylearn'),
        ),
        migrations.AddField(
            model_name='searchkey',
            name='rating',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Learning_ORM_queries.rating'),
            preserve_default=False,
        ),
    ]
