# Generated by Django 5.0.4 on 2024-06-15 04:06

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0064_searchkey_proxy_learn_searchkey_rating'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='searchkey',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('search_keyword', 'full_description', config='english'), name='search_vector_idx'),
        ),
    ]
