# Generated by Django 5.0.4 on 2024-06-15 04:09

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0065_searchkey_search_vector_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchkey',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, editable=False, null=True),
        ),
        migrations.AddIndex(
            model_name='searchkey',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='Learning_OR_search__a365d7_gin'),
        ),
    ]
