# Generated by Django 5.0.4 on 2024-06-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0067_queryexps'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryexps',
            name='nos',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
    ]
