# Generated by Django 5.0.4 on 2024-06-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0068_queryexps_nos'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryexps',
            name='verified',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
