# Generated by Django 5.0.4 on 2024-06-22 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0070_explearn1'),
    ]

    operations = [
        migrations.AddField(
            model_name='explearn1',
            name='name',
            field=models.CharField(default='ss', max_length=100),
            preserve_default=False,
        ),
    ]
