# Generated by Django 5.0.4 on 2024-06-22 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0072_explearn1_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='explearn1',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
