# Generated by Django 5.0.4 on 2024-06-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0075_learndatedbfunc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DbMathFunc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_value', models.IntegerField()),
                ('float_value', models.FloatField()),
                ('floor_no', models.IntegerField()),
                ('weight', models.FloatField()),
            ],
        ),
    ]
