# Generated by Django 5.0.4 on 2024-06-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0076_dbmathfunc'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbmathfunc',
            name='description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
    ]
