# Generated by Django 5.0.4 on 2024-06-23 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0078_dbmathfunc_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearnManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('int_value', models.IntegerField()),
                ('floor_no', models.IntegerField()),
            ],
        ),
    ]
