# Generated by Django 5.0.4 on 2024-06-23 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0081_managerdetail_managerdetailmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='learnmanager',
            name='manager_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Learning_ORM_queries.managerdetail'),
        ),
    ]
