# Generated by Django 5.0.4 on 2024-06-23 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0082_learnmanager_manager_detail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ManagerDetailManager',
        ),
    ]
