# Generated by Django 5.0.4 on 2024-06-23 06:48

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0083_delete_managerdetailmanager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerdetail',
            options={'base_manager_name': 'base_manager'},
        ),
        migrations.AlterModelManagers(
            name='managerdetail',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
