# Generated by Django 5.0.4 on 2024-06-23 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0084_alter_managerdetail_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='managerdetail',
            options={},
        ),
        migrations.AlterModelManagers(
            name='managerdetail',
            managers=[
            ],
        ),
    ]
