# Generated by Django 5.0.4 on 2024-06-23 13:45

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0086_alter_managerdetail_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildLearnManager',
            fields=[
                ('learnmanager_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Learning_ORM_queries.learnmanager')),
                ('child_name', models.CharField(max_length=100)),
            ],
            bases=('Learning_ORM_queries.learnmanager',),
            managers=[
                ('my_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
