# Generated by Django 5.0.4 on 2024-06-24 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Learning_ORM_queries', '0088_dbtransactions_alter_childlearnmanager_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbtransactions',
            name='title',
            field=models.CharField(max_length=10),
        ),
    ]
